/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista.VENTAS.CAJA;

import CLASES_GLOBALES.METODOS_GLOBALES;
import static CLASES_GLOBALES.METODOS_GLOBALES.Fecha;
import static CLASES_GLOBALES.METODOS_GLOBALES.Hora;
import static CLASES_GLOBALES.METODOS_GLOBALES.executorService;
import CLASES_GLOBALES.PARAMETROS_USUARIOS;
import static CLASES_GLOBALES.PARAMETROS_USUARIOS.ID_USUARIO;
import CLASES_GLOBALES.PARAMETROS_VENTAS;
import CONSULTAS.CONSULTAS_CAJA;
import Controlador.CajaDao;
import Controlador.Eventos;
import Controlador.FullSelectorListener;
import Modelo.CAJA;
import Vista.ADMINISTRACION.PROVEEDORES.HISTORIAL_GASTOS;
import Vista.AVISOS;
import java.awt.Color;
import java.text.DecimalFormat;
import java.util.Objects;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author aldoy
 */
public final class ADMINISTRAR_CAJA extends javax.swing.JDialog {

    DecimalFormat formatea = new DecimalFormat("###,###.##");
    String NUMERO_CAJA, Fecha, TotalInicial;
    Float TOTAL_FINAL_EN_CAJA = 0F, TOTAL_FINAL = 0F;
    int Usuario;
    AVISOS AV;
    INTERNAL_CAJA_PRINCIPAL CAJA_PRINCIPAL;

    public ADMINISTRAR_CAJA(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public ADMINISTRAR_CAJA(java.awt.Frame parent, boolean modal, String NUMERO_CAJA, String Total_Inicial, String Fecha, Boolean EDITAR, INTERNAL_CAJA_PRINCIPAL CAJA_PRINCIPAL) {
        super(parent, modal);
        initComponents();
        this.CAJA_PRINCIPAL = CAJA_PRINCIPAL;
        VALIDAR_CAJAS(jPanel4, EDITAR);
        this.TotalInicial = Total_Inicial;
        this.Usuario = ID_USUARIO;
        this.Fecha = Fecha;
        this.jTextField9.setText(Total_Inicial);
        this.setLocationRelativeTo(parent);
        this.NUMERO_CAJA = NUMERO_CAJA;
        jLabel2.setText(jLabel2.getText()+ " #"+this.NUMERO_CAJA);
        if(EDITAR==false){
            CONSULTAR_DATOS(EDITAR);
        }else{
            CONSULTAR_DATOS(EDITAR);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        caja_TotalEfectivo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        caja_TotalTransferencia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        caja_TotalCheque = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        caja_TotalTarjeta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        caja_TotalCompartido = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        caja_TotalCostos = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        caja_TotalGanancias = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        caja_TotalPersonalizados = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        caja_CantidadTotalPersonalizados = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(701, 647));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosSOciales/CAJA_32PX.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AJUSTE DE CAJA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "TOTALES"));

        caja_TotalEfectivo.setText("0.00");
        caja_TotalEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_TotalEfectivoActionPerformed(evt);
            }
        });
        caja_TotalEfectivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caja_TotalEfectivoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_TotalEfectivoKeyTyped(evt);
            }
        });

        jLabel3.setText("TOTAL EN EFECTIVO:");

        jLabel4.setText("TOTAL TRANS/DEP:");

        caja_TotalTransferencia.setText("0.00");
        caja_TotalTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_TotalTransferenciaActionPerformed(evt);
            }
        });
        caja_TotalTransferencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caja_TotalTransferenciaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_TotalTransferenciaKeyTyped(evt);
            }
        });

        jLabel5.setText("TOTAL EN CHEQUE:");

        caja_TotalCheque.setText("0.00");
        caja_TotalCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_TotalChequeActionPerformed(evt);
            }
        });
        caja_TotalCheque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caja_TotalChequeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_TotalChequeKeyTyped(evt);
            }
        });

        jLabel6.setText("TOTAL EN TARJETA:");

        caja_TotalTarjeta.setText("0.00");
        caja_TotalTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_TotalTarjetaActionPerformed(evt);
            }
        });
        caja_TotalTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caja_TotalTarjetaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_TotalTarjetaKeyTyped(evt);
            }
        });

        jLabel7.setText("TOTAL CAMBIOS:");

        caja_TotalCompartido.setEditable(false);
        caja_TotalCompartido.setText("0.00");
        caja_TotalCompartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_TotalCompartidoActionPerformed(evt);
            }
        });
        caja_TotalCompartido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caja_TotalCompartidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_TotalCompartidoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caja_TotalCompartido)
                    .addComponent(caja_TotalCheque, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(caja_TotalTransferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(caja_TotalTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(caja_TotalEfectivo))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(caja_TotalEfectivo, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(caja_TotalTransferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(caja_TotalCheque)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(caja_TotalTarjeta)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(caja_TotalCompartido)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "RESUMEN"));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField5.setText("0.00");

        jLabel8.setText("TOTAL VENTAS (+):");

        jTextField6.setEditable(false);
        jTextField6.setText("0.00");

        jLabel9.setText("TOTAL COMPRAS (-):");

        jLabel10.setText("TOTAL SALIDAS (-):");

        jTextField7.setEditable(false);
        jTextField7.setText("0.00");

        jTextField8.setEditable(false);
        jTextField8.setText("0.00");

        jTextField9.setEditable(false);
        jTextField9.setText("0.00");

        jLabel12.setText("TOTAL INICIAL:");

        jLabel15.setText("TOTAL (=):");

        jLabel13.setText("TOTAL ENTRADAS (+):");

        jTextField10.setEditable(false);
        jTextField10.setText("0.00");
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField10)
                            .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                            .addComponent(jTextField6)
                            .addComponent(jTextField7)
                            .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "VALIDACIÓN")));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosSOciales/BUEN_TRABAJO_GIFT.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "GANANCIAS"));

        caja_TotalCostos.setEditable(false);
        caja_TotalCostos.setText("0.00");
        caja_TotalCostos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_TotalCostosActionPerformed(evt);
            }
        });
        caja_TotalCostos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caja_TotalCostosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_TotalCostosKeyTyped(evt);
            }
        });

        jLabel16.setText("TOTAL DE COSTOS:");

        jLabel17.setText("TOTAL DE GANANCIAS:");

        caja_TotalGanancias.setEditable(false);
        caja_TotalGanancias.setText("0.00");
        caja_TotalGanancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_TotalGananciasActionPerformed(evt);
            }
        });
        caja_TotalGanancias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caja_TotalGananciasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_TotalGananciasKeyTyped(evt);
            }
        });

        jLabel18.setText("TOTAL INGRESADOS PERSONALIZADOS:");

        caja_TotalPersonalizados.setEditable(false);
        caja_TotalPersonalizados.setText("0.00");
        caja_TotalPersonalizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_TotalPersonalizadosActionPerformed(evt);
            }
        });
        caja_TotalPersonalizados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caja_TotalPersonalizadosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_TotalPersonalizadosKeyTyped(evt);
            }
        });

        jLabel19.setText("CANTIDAD INGRESADOS PERSONALIZADOS:");

        caja_CantidadTotalPersonalizados.setEditable(false);
        caja_CantidadTotalPersonalizados.setText("0.00");
        caja_CantidadTotalPersonalizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_CantidadTotalPersonalizadosActionPerformed(evt);
            }
        });
        caja_CantidadTotalPersonalizados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caja_CantidadTotalPersonalizadosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_CantidadTotalPersonalizadosKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caja_TotalPersonalizados)
                    .addComponent(caja_TotalGanancias)
                    .addComponent(caja_TotalCostos)
                    .addComponent(caja_CantidadTotalPersonalizados))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(caja_TotalCostos, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(caja_TotalGanancias, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(caja_CantidadTotalPersonalizados)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(caja_TotalPersonalizados)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosSOciales/ACEPTAR_48PX.png"))); // NOI18N
        jButton1.setMnemonic('A');
        jButton1.setText("CERRAR CAJA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosSOciales/CANCELAR_48PX.png"))); // NOI18N
        jButton2.setMnemonic('C');
        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosSOciales/IMPRESORA_32PX.png"))); // NOI18N
        jButton4.setText("IMPRIMIR DETALLES");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosSOciales/gmail_new_logo_icon_159149.png"))); // NOI18N
        jButton5.setText("ENVIAR POR GMAIL");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosSOciales/iconfinder-documents01-1622837_121952.png"))); // NOI18N
        jButton6.setText("GUARDAR PDF");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jMenu2.setText("ACCIÓNES");

        jMenuItem2.setText("ACTUALIZAR");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);
        jMenu2.add(jSeparator1);

        jMenuItem1.setText("REAPERTURAR CAJA");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);
        jMenu2.add(jSeparator3);

        jMenuItem4.setText("OBTENER PAGOS");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("DETALLES");

        jMenuItem3.setText("VER DETALLES DE ENTRADAS Y SALIDAS");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator4);

        jMenuItem5.setText("VIGENTES Y ANULADOS");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void LIMPIAR_CAJAS(JPanel panel, boolean AGREGAR_LABEL){
        for(int i = 0; panel.getComponents().length > i; i++){
            if(panel.getComponents()[i] instanceof JTextField){
                ((JTextField)panel.getComponents()[i]).setText("0.00");
            }
            else if(panel.getComponents()[i] instanceof JPasswordField){
                ((JPasswordField)panel.getComponents()[i]).setText("0.00");
            }
            if(AGREGAR_LABEL==true){
              if(panel.getComponents()[i] instanceof JLabel){
                ((JLabel)panel.getComponents()[i]).setText("SIN DATOS");
            }  
            }
        }
        caja_TotalCompartido.setEnabled(false);
    }
    
    public void VALIDAR_CAJAS(JPanel panel, boolean EDITAR){
        for(int i = 0; panel.getComponents().length > i; i++){
            if(panel.getComponents()[i] instanceof JTextField){
                ((JTextField)panel.getComponents()[i]).setEditable(EDITAR);
            }
            else if(panel.getComponents()[i] instanceof JPasswordField){
                ((JPasswordField)panel.getComponents()[i]).setEditable(EDITAR);
            }
            if(EDITAR == true){
                jSeparator1.setVisible(false);
                jMenuItem1.setVisible(false);
                jPanel7.setVisible(false);
            }else{
                jSeparator1.setVisible(true);
                jMenuItem1.setVisible(true);
                jPanel7.setVisible(true);
            }
            jPanel3.setVisible(EDITAR);
        }
    }

    public void CONSULTAR_DATOS(Boolean ESTADO) {

        if (ESTADO == true) {
            CARGAR_PAGOS();
        } else {
            CONSULTAS_CAJA C_C = new CONSULTAS_CAJA();
            CAJA caja = new CAJA();
            caja = C_C.CAJA_CONSULTA_NUMERO(Integer.parseInt(NUMERO_CAJA));
            caja_TotalEfectivo.setText(String.valueOf(caja.getTotal_Efectivo_CAJA()));
            caja_TotalTransferencia.setText(String.valueOf(caja.getTotal_Transferencia_CAJA()));
            caja_TotalCheque.setText(String.valueOf(caja.getTotal_Cheque_CAJA()));
            caja_TotalTarjeta.setText(String.valueOf(caja.getTotal_Tarjeta_CAJA()));
            caja_TotalCompartido.setText(String.valueOf(caja.getTotal_Compartido_CAJA()));
        }
        CARGAR_TOTALES();
        SUMAR_CANTIDADES();
        ARQUEO_DE_CAJA();
    } 
    
    public void CARGAR_PAGOS(){
        CONSULTAS_CAJA C_C= new CONSULTAS_CAJA();
        Float EfectivoEnCaja = C_C.Total_EFECTIVO(Integer.parseInt(NUMERO_CAJA))+C_C.Total_ENTRADAS(Integer.parseInt(NUMERO_CAJA));
        caja_TotalEfectivo.setText(String.valueOf(EfectivoEnCaja));
        caja_TotalCheque.setText(C_C.Total_CHEQUE(Integer.parseInt(NUMERO_CAJA)).toString());
        caja_TotalTarjeta.setText(C_C.Total_TARJETA(Integer.parseInt(NUMERO_CAJA)).toString());
        caja_TotalTransferencia.setText(C_C.Total_TRANSFERENCIA(Integer.parseInt(NUMERO_CAJA)).toString());
        caja_TotalCompartido.setText(C_C.Total_COMPARTIDO(Integer.parseInt(NUMERO_CAJA)).toString());
    }

    public void CARGAR_TOTALES() {
        CARGAR_VENTAS();
        CARGAR_COMPRAS();
        CARGAR_SALIDAS();
        CARGAR_ENTRADAS();
        OPERACIONES();
        executorService.execute(new Runnable() {
            @Override
            public void run() {
                executorService.execute(() -> {

                    CARGAR_GANANCIAS();
                    CARGAR_COSTOS();
                    CARGAR_CANTIDAD_PRODUCTOS_PERSONALIZADOS();
                    CARGAR_TOTAL_PRODUCTOS_PERSONALIZADOS();
                    SUMAR_CANTIDADES();
                    ARQUEO_DE_CAJA();
                });
            }
        });

    }

    public void CARGAR_VENTAS(){
        CONSULTAS_CAJA C_C= new CONSULTAS_CAJA();
        jTextField6.setText(C_C.Total_Ventas(Integer.parseInt(NUMERO_CAJA)).toString());
    }
    
    public void CARGAR_COMPRAS(){
        CONSULTAS_CAJA C_C= new CONSULTAS_CAJA();
        jTextField7.setText(C_C.Total_Compras(Integer.parseInt(NUMERO_CAJA)).toString());
    }
    
    public void CARGAR_SALIDAS(){
        CONSULTAS_CAJA C_C= new CONSULTAS_CAJA();
        jTextField8.setText(C_C.Total_SALIDAS(Integer.parseInt(NUMERO_CAJA)).toString());
    }
    
    public void CARGAR_ENTRADAS(){
        CONSULTAS_CAJA C_C= new CONSULTAS_CAJA();
        jTextField10.setText(C_C.Total_ENTRADAS(Integer.parseInt(NUMERO_CAJA)).toString());
    }
    
    public void CARGAR_GANANCIAS(){
        CONSULTAS_CAJA C_C= new CONSULTAS_CAJA();
        caja_TotalGanancias.setText(formatea.format(C_C.Total_GANANCIAS(Integer.parseInt(NUMERO_CAJA))));
    }
    
    public void CARGAR_COSTOS(){
        CONSULTAS_CAJA C_C= new CONSULTAS_CAJA();
        caja_TotalCostos.setText(formatea.format(C_C.Total_COSTOS(Integer.parseInt(NUMERO_CAJA))));
    }
    public void CARGAR_CANTIDAD_PRODUCTOS_PERSONALIZADOS(){
        CONSULTAS_CAJA C_C= new CONSULTAS_CAJA();
        caja_CantidadTotalPersonalizados.setText(formatea.format(C_C.Total_CANTIDAD_PRODUCTOS_PERSONALIZADOS(Integer.parseInt(NUMERO_CAJA))));
    }
    
    public void CARGAR_TOTAL_PRODUCTOS_PERSONALIZADOS(){
        CONSULTAS_CAJA C_C= new CONSULTAS_CAJA();
        caja_TotalPersonalizados.setText(formatea.format(C_C.Total_TOTAL_PRODUCTOS_PERSONALIZADOS(Integer.parseInt(NUMERO_CAJA))));
    }
    
    public void OPERACIONES(){
        TOTAL_FINAL = Float.parseFloat(TotalInicial)+Float.parseFloat(jTextField6.getText())+Float.parseFloat(jTextField10.getText())-Float.parseFloat(jTextField7.getText())-Float.parseFloat(jTextField8.getText());
        jTextField5.setText(TOTAL_FINAL.toString());
    }
    
    public void CARGAR_VENTAS_TARJETA(){
        CONSULTAS_CAJA C_C= new CONSULTAS_CAJA();
        caja_TotalEfectivo.setText(C_C.Total_Ventas(Integer.parseInt(NUMERO_CAJA)).toString());
    }
    
    public String SUMAR_CANTIDADES(){
        String Total = jTextField5.getText();
        if(METODOS_GLOBALES.VERIFICAR_LLENADO_CAJAS(jPanel4) == true){
          try {
            TOTAL_FINAL_EN_CAJA = Float.parseFloat(caja_TotalEfectivo.getText()) + Float.parseFloat(caja_TotalTransferencia.getText())
                + Float.parseFloat(caja_TotalCheque.getText()) + Float.parseFloat(caja_TotalTarjeta.getText()) - Float.parseFloat(caja_TotalCompartido.getText());
        
        Total = String.valueOf(TOTAL_FINAL_EN_CAJA - TOTAL_FINAL);
        } catch (NumberFormatException e) {
            System.out.println(e.fillInStackTrace());
        }  
        }
        
        return Total;
    }

    public void ARQUEO_DE_CAJA() {
        if (Objects.equals(TOTAL_FINAL_EN_CAJA, TOTAL_FINAL)) {
            jLabel11.setText("AJUSTADO: " + SUMAR_CANTIDADES());
            jLabel11.setHorizontalTextPosition(2);
            jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosSOciales/BUEN_TRABAJO_GIFT.gif")));
            jLabel11.setForeground(Color.GREEN);
            jButton1.setEnabled(true);
        }else if (TOTAL_FINAL_EN_CAJA > TOTAL_FINAL) {
            jLabel11.setText("SOBRANTE: " + SUMAR_CANTIDADES());
            jLabel11.setHorizontalTextPosition(2);
            jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosSOciales/DUDA_GIFT_1.gif")));
            jLabel11.setForeground(Color.MAGENTA);
            jButton1.setEnabled(true);
        } else if (TOTAL_FINAL_EN_CAJA < TOTAL_FINAL){
            jLabel11.setText("FALTANTE: " + SUMAR_CANTIDADES());
            jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosSOciales/SUSTO_GIFT.gif")));
            jLabel11.setForeground(Color.red);
            jButton1.setEnabled(false);
        }

    }
    
    public void CERRAR_CAJA(){
        CajaDao CDao= new CajaDao();
        CAJA caja= new CAJA();
        caja.setESTADO_DE_CAJA("CERRADA");
        caja.setFECHA_HORA_CIERRE_CAJA(Fecha()+" "+Hora());
        caja.setUSUARIO_CERRO_CAJA(PARAMETROS_USUARIOS.ID_USUARIO);
        caja.setARQUEO_DE_CAJA(jLabel11.getText());
        caja.setTotal_Ventas_CAJA(Float.parseFloat(jTextField6.getText()));
        caja.setTotal_Compras_CAJA(Float.parseFloat(jTextField7.getText()));
        caja.setTotal_Gastos_CAJA(Float.parseFloat(jTextField8.getText()));
        caja.setTotal_Efectivo_CAJA(Float.parseFloat(caja_TotalEfectivo.getText()));
        caja.setTotal_Transferencia_CAJA(Float.parseFloat(caja_TotalTransferencia.getText()));
        caja.setTotal_Cheque_CAJA(Float.parseFloat(caja_TotalCheque.getText()));
        caja.setTotal_Tarjeta_CAJA(Float.parseFloat(caja_TotalTarjeta.getText()));
        caja.setTotal_Compartido_CAJA(Float.parseFloat(caja_TotalCompartido.getText()));
        caja.setIdcaja(Integer.parseInt(NUMERO_CAJA));
        CDao.EDITAR_CIERRES_DE_CAJA(caja);
        PARAMETROS_VENTAS.NUMERO_CAJA = "";
        CAJA_PRINCIPAL.principal.jLabel4.setText(PARAMETROS_VENTAS.NUMERO_CAJA);
        CAJA_PRINCIPAL.ACTUALIZAR_CAJAS();
        CAJA_PRINCIPAL.VALIDAR_BOTONES(1);
        this.dispose();
    }
    
    public void REABRIR(){
        CajaDao CDao= new CajaDao();
        CAJA caja= new CAJA();
        caja.setESTADO_DE_CAJA("APERTURADO");
        caja.setFECHA_HORA_CIERRE_CAJA(null);
        caja.setUSUARIO_CERRO_CAJA(PARAMETROS_USUARIOS.ID_USUARIO);
        caja.setARQUEO_DE_CAJA(jLabel11.getText());
        caja.setIdcaja(Integer.parseInt(NUMERO_CAJA));
        CDao.REAPERTURAR_CAJA(caja);
        CAJA_PRINCIPAL.ACTUALIZAR_CAJAS();
        CAJA_PRINCIPAL.VALIDAR_BOTONES(1);
        CARGAR_TOTALES();
        VALIDAR_CAJAS(jPanel4, true);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CERRAR_CAJA();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CARGAR_TOTALES();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void caja_TotalEfectivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_TotalEfectivoKeyReleased
        if(caja_TotalEfectivo.getText() != ""){
            METODOS_GLOBALES.DESVACIAR_CAJAS(jPanel4);
            SUMAR_CANTIDADES();
            ARQUEO_DE_CAJA();
        }
    }//GEN-LAST:event_caja_TotalEfectivoKeyReleased

    private void caja_TotalTransferenciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_TotalTransferenciaKeyReleased
        if(caja_TotalTransferencia.getText() == ""){
        }else{
            METODOS_GLOBALES.DESVACIAR_CAJAS(jPanel4);
            SUMAR_CANTIDADES();
            ARQUEO_DE_CAJA();
        }
    }//GEN-LAST:event_caja_TotalTransferenciaKeyReleased

    private void caja_TotalChequeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_TotalChequeKeyReleased
        if(caja_TotalCheque.getText() == ""){
            
        }else{
            METODOS_GLOBALES.DESVACIAR_CAJAS(jPanel4);
            SUMAR_CANTIDADES();
            ARQUEO_DE_CAJA();
        }
    }//GEN-LAST:event_caja_TotalChequeKeyReleased

    private void caja_TotalTarjetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_TotalTarjetaKeyReleased
        if(caja_TotalTarjeta.getText() == ""){
        }else{
            METODOS_GLOBALES.DESVACIAR_CAJAS(jPanel4);
            SUMAR_CANTIDADES();
            ARQUEO_DE_CAJA();
        }
    }//GEN-LAST:event_caja_TotalTarjetaKeyReleased

    private void caja_TotalEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_TotalEfectivoActionPerformed
        caja_TotalEfectivo.addFocusListener(new FullSelectorListener());
    }//GEN-LAST:event_caja_TotalEfectivoActionPerformed

    private void caja_TotalTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_TotalTransferenciaActionPerformed
        caja_TotalTransferencia.addFocusListener(new FullSelectorListener());
    }//GEN-LAST:event_caja_TotalTransferenciaActionPerformed

    private void caja_TotalChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_TotalChequeActionPerformed
        caja_TotalCheque.addFocusListener(new FullSelectorListener());
    }//GEN-LAST:event_caja_TotalChequeActionPerformed

    private void caja_TotalTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_TotalTarjetaActionPerformed
        caja_TotalTarjeta.addFocusListener(new FullSelectorListener());
    }//GEN-LAST:event_caja_TotalTarjetaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        REABRIR();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void caja_TotalEfectivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_TotalEfectivoKeyTyped
        Eventos event = new Eventos();
        event.numberDecimalKeyPress(evt, caja_TotalEfectivo);
    }//GEN-LAST:event_caja_TotalEfectivoKeyTyped

    private void caja_TotalTransferenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_TotalTransferenciaKeyTyped
        Eventos event = new Eventos();
        event.numberDecimalKeyPress(evt, caja_TotalTransferencia);
    }//GEN-LAST:event_caja_TotalTransferenciaKeyTyped

    private void caja_TotalChequeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_TotalChequeKeyTyped
        Eventos event = new Eventos();
        event.numberDecimalKeyPress(evt, caja_TotalCheque);
    }//GEN-LAST:event_caja_TotalChequeKeyTyped

    private void caja_TotalTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_TotalTarjetaKeyTyped
       Eventos event = new Eventos();
        event.numberDecimalKeyPress(evt, caja_TotalTarjeta);
    }//GEN-LAST:event_caja_TotalTarjetaKeyTyped

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        HISTORIAL_GASTOS H_G = new HISTORIAL_GASTOS(null, true, Integer.parseInt(NUMERO_CAJA));
        H_G.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        CARGAR_PAGOS();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        VER_DETALLES_VIGENTES_ANULADOS D_V_A = new VER_DETALLES_VIGENTES_ANULADOS(null, true, Integer.parseInt(NUMERO_CAJA));
        D_V_A.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void caja_TotalCompartidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_TotalCompartidoKeyReleased
        if(caja_TotalCompartido.getText() == ""){
        }else{
            METODOS_GLOBALES.DESVACIAR_CAJAS(jPanel4);
            SUMAR_CANTIDADES();
            ARQUEO_DE_CAJA();
        }
    }//GEN-LAST:event_caja_TotalCompartidoKeyReleased

    private void caja_TotalCompartidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_TotalCompartidoKeyTyped
        Eventos event = new Eventos();
        event.numberDecimalKeyPress(evt, caja_TotalTarjeta);
    }//GEN-LAST:event_caja_TotalCompartidoKeyTyped

    private void caja_TotalCompartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_TotalCompartidoActionPerformed
        caja_TotalCheque.addFocusListener(new FullSelectorListener());
    }//GEN-LAST:event_caja_TotalCompartidoActionPerformed

    private void caja_TotalCostosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_TotalCostosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_TotalCostosActionPerformed

    private void caja_TotalCostosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_TotalCostosKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_TotalCostosKeyReleased

    private void caja_TotalCostosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_TotalCostosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_TotalCostosKeyTyped

    private void caja_TotalGananciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_TotalGananciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_TotalGananciasActionPerformed

    private void caja_TotalGananciasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_TotalGananciasKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_TotalGananciasKeyReleased

    private void caja_TotalGananciasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_TotalGananciasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_TotalGananciasKeyTyped

    private void caja_TotalPersonalizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_TotalPersonalizadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_TotalPersonalizadosActionPerformed

    private void caja_TotalPersonalizadosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_TotalPersonalizadosKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_TotalPersonalizadosKeyReleased

    private void caja_TotalPersonalizadosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_TotalPersonalizadosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_TotalPersonalizadosKeyTyped

    private void caja_CantidadTotalPersonalizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_CantidadTotalPersonalizadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_CantidadTotalPersonalizadosActionPerformed

    private void caja_CantidadTotalPersonalizadosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_CantidadTotalPersonalizadosKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_CantidadTotalPersonalizadosKeyReleased

    private void caja_CantidadTotalPersonalizadosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_CantidadTotalPersonalizadosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_CantidadTotalPersonalizadosKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JOptionPane.showMessageDialog(this, "FUNCIÓN EN DESARROLLO, ESPERAMOS TENERLO EN LA PROXIMA VERSIÓN, GRACIAS!", "EN DESARROLLO", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JOptionPane.showMessageDialog(this, "FUNCIÓN EN DESARROLLO, ESPERAMOS TENERLO EN LA PROXIMA VERSIÓN, GRACIAS!", "EN DESARROLLO", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JOptionPane.showMessageDialog(this, "FUNCIÓN EN DESARROLLO, ESPERAMOS TENERLO EN LA PROXIMA VERSIÓN, GRACIAS!", "EN DESARROLLO", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMINISTRAR_CAJA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMINISTRAR_CAJA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMINISTRAR_CAJA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMINISTRAR_CAJA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ADMINISTRAR_CAJA dialog = new ADMINISTRAR_CAJA(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField caja_CantidadTotalPersonalizados;
    private javax.swing.JTextField caja_TotalCheque;
    private javax.swing.JTextField caja_TotalCompartido;
    private javax.swing.JTextField caja_TotalCostos;
    private javax.swing.JTextField caja_TotalEfectivo;
    private javax.swing.JTextField caja_TotalGanancias;
    private javax.swing.JTextField caja_TotalPersonalizados;
    private javax.swing.JTextField caja_TotalTarjeta;
    private javax.swing.JTextField caja_TotalTransferencia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
