/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista.ADMINISTRACION.INVENTARIO;

import CLASES_GLOBALES.PARAMETROS_EMPRESA;
import java.text.DecimalFormat;
import javax.swing.JTable;

/**
 *
 * @author aldoy
 */
public class TOTALES extends javax.swing.JInternalFrame {
    
    public TOTALES() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }

    public void TOTALES_INVENTARIO(JTable TABLA) {
        DecimalFormat formatea = new DecimalFormat("###,###.##");
        int nu = TABLA.getRowCount();

        TotalRegistrados.setText("" + nu);

        Double TotalStock23 = 0.00;
        Double TotalCosto = 0.00;
        Double TotalCosto2 = 0.00;
        Double TotalPublicosAmigo = 0.00;
        for (int i = 0; i < nu; i++) {
            double cal = Double.parseDouble(String.valueOf(TABLA.getModel().getValueAt(i, 2)));
            TotalStock23 = TotalStock23 + cal;

        }
        TotalStock.setText(formatea.format(TotalStock23));

        for (int i = 0; i < nu; i++) {
            double cal = Double.parseDouble(String.valueOf(TABLA.getModel().getValueAt(i, 3)));
            double todo = Double.parseDouble(String.valueOf(TABLA.getModel().getValueAt(i, 2)));
            TotalCosto = TotalCosto + cal * todo;

        }
        TotalCostos.setText(PARAMETROS_EMPRESA.SIGNO_MONEDA + formatea.format(TotalCosto));

        for (int i = 0; i < nu; i++) {
            double cal = Double.parseDouble(String.valueOf(TABLA.getModel().getValueAt(i, 5)));
            double todo = Double.parseDouble(String.valueOf(TABLA.getModel().getValueAt(i, 2)));
            TotalPublicosAmigo = TotalPublicosAmigo + cal * todo;

        }
        TotalPublicos.setText(PARAMETROS_EMPRESA.SIGNO_MONEDA + formatea.format(TotalPublicosAmigo));
        Double TotalGanancias = TotalPublicosAmigo - TotalCosto;
        TotalGananciasNumeros.setText(PARAMETROS_EMPRESA.SIGNO_MONEDA + formatea.format(TotalGanancias));
        TotalGananciasPorcentaje.setText(PorcentajesTotal(TotalCosto, TotalPublicosAmigo));
    }
    
    public static String PorcentajesTotal(Double ValorUno, Double ValorDos){
        
        Double Total = ((ValorDos-ValorUno)/ValorUno)*100;
        String TotalPorcentaje = String.format("%.2f", Total )+ "%";
        return TotalPorcentaje;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PANEL_TOTALES = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        lGJPanelGradientBassic3 = new components.LGJPanelGradientBassic();
        jLabel64 = new javax.swing.JLabel();
        TotalRegistrados = new javax.swing.JLabel();
        lGJPanelGradientBassic4 = new components.LGJPanelGradientBassic();
        jLabel68 = new javax.swing.JLabel();
        TotalStock = new javax.swing.JLabel();
        lGJPanelGradientBassic5 = new components.LGJPanelGradientBassic();
        jLabel69 = new javax.swing.JLabel();
        TotalCostos = new javax.swing.JLabel();
        lGJPanelGradientBassic6 = new components.LGJPanelGradientBassic();
        jLabel70 = new javax.swing.JLabel();
        TotalPublicos = new javax.swing.JLabel();
        lGJPanelGradientBassic7 = new components.LGJPanelGradientBassic();
        jLabel71 = new javax.swing.JLabel();
        TotalGananciasNumeros = new javax.swing.JLabel();
        lGJPanelGradientBassic8 = new components.LGJPanelGradientBassic();
        jLabel72 = new javax.swing.JLabel();
        TotalGananciasPorcentaje = new javax.swing.JLabel();

        setBorder(null);

        jPanel44.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel44.setLayout(new java.awt.GridLayout(2, 3, 5, 5));

        lGJPanelGradientBassic3.setLGGradientColorOne(new java.awt.Color(0, 198, 137));
        lGJPanelGradientBassic3.setLGGradientColorTwo(new java.awt.Color(0, 198, 137));

        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("TOTAL DE PRODUCTOS REGISTRADOS");

        TotalRegistrados.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TotalRegistrados.setForeground(new java.awt.Color(255, 255, 255));
        TotalRegistrados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalRegistrados.setText("TOTAL EN STOCK");

        javax.swing.GroupLayout lGJPanelGradientBassic3Layout = new javax.swing.GroupLayout(lGJPanelGradientBassic3);
        lGJPanelGradientBassic3.setLayout(lGJPanelGradientBassic3Layout);
        lGJPanelGradientBassic3Layout.setHorizontalGroup(
            lGJPanelGradientBassic3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lGJPanelGradientBassic3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lGJPanelGradientBassic3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel64, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TotalRegistrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );
        lGJPanelGradientBassic3Layout.setVerticalGroup(
            lGJPanelGradientBassic3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lGJPanelGradientBassic3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalRegistrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel44.add(lGJPanelGradientBassic3);

        lGJPanelGradientBassic4.setLGGradientColorOne(new java.awt.Color(255, 51, 51));
        lGJPanelGradientBassic4.setLGGradientColorTwo(new java.awt.Color(255, 51, 51));

        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("TOTAL EN STOCK");

        TotalStock.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TotalStock.setForeground(new java.awt.Color(255, 255, 255));
        TotalStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalStock.setText("TOTAL EN STOCK");

        javax.swing.GroupLayout lGJPanelGradientBassic4Layout = new javax.swing.GroupLayout(lGJPanelGradientBassic4);
        lGJPanelGradientBassic4.setLayout(lGJPanelGradientBassic4Layout);
        lGJPanelGradientBassic4Layout.setHorizontalGroup(
            lGJPanelGradientBassic4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lGJPanelGradientBassic4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lGJPanelGradientBassic4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel68, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TotalStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );
        lGJPanelGradientBassic4Layout.setVerticalGroup(
            lGJPanelGradientBassic4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lGJPanelGradientBassic4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel68)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel44.add(lGJPanelGradientBassic4);

        lGJPanelGradientBassic5.setLGGradientColorOne(new java.awt.Color(255, 123, 0));
        lGJPanelGradientBassic5.setLGGradientColorTwo(new java.awt.Color(255, 123, 0));

        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("PATRIMONIO / COSTOS");

        TotalCostos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TotalCostos.setForeground(new java.awt.Color(255, 255, 255));
        TotalCostos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalCostos.setText("TOTAL");

        javax.swing.GroupLayout lGJPanelGradientBassic5Layout = new javax.swing.GroupLayout(lGJPanelGradientBassic5);
        lGJPanelGradientBassic5.setLayout(lGJPanelGradientBassic5Layout);
        lGJPanelGradientBassic5Layout.setHorizontalGroup(
            lGJPanelGradientBassic5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lGJPanelGradientBassic5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lGJPanelGradientBassic5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TotalCostos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel69, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        lGJPanelGradientBassic5Layout.setVerticalGroup(
            lGJPanelGradientBassic5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lGJPanelGradientBassic5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel69)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalCostos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel44.add(lGJPanelGradientBassic5);

        lGJPanelGradientBassic6.setLGGradientColorOne(new java.awt.Color(51, 153, 255));
        lGJPanelGradientBassic6.setLGGradientColorTwo(new java.awt.Color(204, 204, 255));

        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("TOTAL DE PUBLICO");

        TotalPublicos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TotalPublicos.setForeground(new java.awt.Color(255, 255, 255));
        TotalPublicos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalPublicos.setText("TOTAL EN STOCK");

        javax.swing.GroupLayout lGJPanelGradientBassic6Layout = new javax.swing.GroupLayout(lGJPanelGradientBassic6);
        lGJPanelGradientBassic6.setLayout(lGJPanelGradientBassic6Layout);
        lGJPanelGradientBassic6Layout.setHorizontalGroup(
            lGJPanelGradientBassic6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lGJPanelGradientBassic6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lGJPanelGradientBassic6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TotalPublicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        lGJPanelGradientBassic6Layout.setVerticalGroup(
            lGJPanelGradientBassic6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lGJPanelGradientBassic6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel70)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalPublicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel44.add(lGJPanelGradientBassic6);

        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("GANANCIAS");

        TotalGananciasNumeros.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TotalGananciasNumeros.setForeground(new java.awt.Color(255, 255, 255));
        TotalGananciasNumeros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalGananciasNumeros.setText("TOTAL EN STOCK");

        javax.swing.GroupLayout lGJPanelGradientBassic7Layout = new javax.swing.GroupLayout(lGJPanelGradientBassic7);
        lGJPanelGradientBassic7.setLayout(lGJPanelGradientBassic7Layout);
        lGJPanelGradientBassic7Layout.setHorizontalGroup(
            lGJPanelGradientBassic7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lGJPanelGradientBassic7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lGJPanelGradientBassic7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel71, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TotalGananciasNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        lGJPanelGradientBassic7Layout.setVerticalGroup(
            lGJPanelGradientBassic7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lGJPanelGradientBassic7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel71)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalGananciasNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel44.add(lGJPanelGradientBassic7);

        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("GANANCIAS %");

        TotalGananciasPorcentaje.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TotalGananciasPorcentaje.setForeground(new java.awt.Color(255, 255, 255));
        TotalGananciasPorcentaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalGananciasPorcentaje.setText("TOTAL EN STOCK");

        javax.swing.GroupLayout lGJPanelGradientBassic8Layout = new javax.swing.GroupLayout(lGJPanelGradientBassic8);
        lGJPanelGradientBassic8.setLayout(lGJPanelGradientBassic8Layout);
        lGJPanelGradientBassic8Layout.setHorizontalGroup(
            lGJPanelGradientBassic8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lGJPanelGradientBassic8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lGJPanelGradientBassic8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel72, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TotalGananciasPorcentaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        lGJPanelGradientBassic8Layout.setVerticalGroup(
            lGJPanelGradientBassic8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lGJPanelGradientBassic8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel72)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalGananciasPorcentaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel44.add(lGJPanelGradientBassic8);

        javax.swing.GroupLayout PANEL_TOTALESLayout = new javax.swing.GroupLayout(PANEL_TOTALES);
        PANEL_TOTALES.setLayout(PANEL_TOTALESLayout);
        PANEL_TOTALESLayout.setHorizontalGroup(
            PANEL_TOTALESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_TOTALESLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel44, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                .addContainerGap())
        );
        PANEL_TOTALESLayout.setVerticalGroup(
            PANEL_TOTALESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANEL_TOTALESLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel44, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(PANEL_TOTALES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(PANEL_TOTALES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PANEL_TOTALES;
    private static javax.swing.JLabel TotalCostos;
    private static javax.swing.JLabel TotalGananciasNumeros;
    private static javax.swing.JLabel TotalGananciasPorcentaje;
    private static javax.swing.JLabel TotalPublicos;
    private static javax.swing.JLabel TotalRegistrados;
    private static javax.swing.JLabel TotalStock;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    public static javax.swing.JPanel jPanel44;
    private components.LGJPanelGradientBassic lGJPanelGradientBassic3;
    private components.LGJPanelGradientBassic lGJPanelGradientBassic4;
    private components.LGJPanelGradientBassic lGJPanelGradientBassic5;
    private components.LGJPanelGradientBassic lGJPanelGradientBassic6;
    private components.LGJPanelGradientBassic lGJPanelGradientBassic7;
    private components.LGJPanelGradientBassic lGJPanelGradientBassic8;
    // End of variables declaration//GEN-END:variables
}
