/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista.ADMINISTRACION.CLIENTES;

import static CONSULTAS.CONSULTAS_TABLAS.ListarClientes;
import Controlador.TextPrompt;
import Vista.Principal;
import static Vista.Principal.ContabilizadorDeVentanasCliente;
import ds.desktop.notify.DesktopNotify;
import ds.desktop.notify.NotifyTheme;
import javax.swing.JButton;

/**
 *
 * @author aldoy
 */
public class CLIENTES extends javax.swing.JInternalFrame {

    /**
     * Creates new form CLIENTES
     */
    public CLIENTES() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }
    
    public static void TextoEnCajaCliente() {
        TextPrompt hold;
        hold = new TextPrompt("NIT-CUI/ID/NOMBRE", nombre1);
    }
    
    public static void CARGAR_CLIENTES(){
        ListarClientes(TablaClientes, TIPO_BUSQUEDA_MODULO_CLIENTES.getText(), nombre1.getText());
        nombre1.requestFocus();
    }
    
    public static void ACTUALIZAR_CLIENTES(){
        TIPO_BUSQUEDA_MODULO_CLIENTES.setText("TODOS");
        nombre1.setText(null);
        ListarClientes(TablaClientes, TIPO_BUSQUEDA_MODULO_CLIENTES.getText(), nombre1.getText());
    }
    
    public static boolean VentanasAbiertasAdministracionClientes(){
        Boolean AbrirVentana= true;
       if(ContabilizadorDeVentanasCliente<1){
        AbrirVentana = true; 
       }else{
           AbrirVentana = false;
           DesktopNotify.setDefaultTheme(NotifyTheme.Light);
                DesktopNotify.showDesktopMessage("ERRÓR", "NO PUEDE ABRIR MÁS DE 1 VENTANA DE ADMINISTRACIÓN DE CLIENTES", DesktopNotify.ERROR, 10000L);
       }
       return AbrirVentana;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel52 = new javax.swing.JPanel();
        nombre1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane14 = new javax.swing.JScrollPane();
        TablaClientes = new javax.swing.JTable();
        TIPO_BUSQUEDA_MODULO_CLIENTES = new javax.swing.JLabel();

        setBorder(null);

        jPanel52.setBackground(new java.awt.Color(51, 153, 255));

        nombre1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        nombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre1ActionPerformed(evt);
            }
        });
        nombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombre1KeyReleased(evt);
            }
        });

        jButton3.setText("NUEVO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton10.setText("ACTUALIZAR");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel52Layout = new javax.swing.GroupLayout(jPanel52);
        jPanel52.setLayout(jPanel52Layout);
        jPanel52Layout.setHorizontalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel52Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombre1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel52Layout.setVerticalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel52Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombre1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "IDENTIFICACION", "TIPO", "DIRECCIÓN", "TEL", "CORREO", "ACCIÓNES"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaClientes.setRowHeight(30);
        TablaClientes.getTableHeader().setReorderingAllowed(false);
        TablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaClientesMouseClicked(evt);
            }
        });
        jScrollPane14.setViewportView(TablaClientes);

        TIPO_BUSQUEDA_MODULO_CLIENTES.setText("TODOS");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TIPO_BUSQUEDA_MODULO_CLIENTES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TIPO_BUSQUEDA_MODULO_CLIENTES)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre1ActionPerformed

    private void nombre1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre1KeyReleased
        TIPO_BUSQUEDA_MODULO_CLIENTES.setText("FILTRADO");
        ListarClientes(TablaClientes, TIPO_BUSQUEDA_MODULO_CLIENTES.getText(), nombre1.getText());
    }//GEN-LAST:event_nombre1KeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(VentanasAbiertasAdministracionClientes() == true){
            Principal.ContabilizadorDeVentanasCliente = 1;
            AdministracionDeCliente ADC = new AdministracionDeCliente(0, 0);
            ADC.setVisible(true);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        ACTUALIZAR_CLIENTES();
        nombre1.requestFocus();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void TablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaClientesMouseClicked
        int fila = TablaClientes.getSelectedRow();
        int Columna = TablaClientes.getColumnModel().getColumnIndexAtX(evt.getX());
        int Fila = evt.getY() / TablaClientes.getRowHeight();
        if (Fila < TablaClientes.getRowCount() && Fila >= 0 && Columna < TablaClientes.getColumnCount() && Columna >= 0) {
            Object value = TablaClientes.getValueAt(Fila, Columna);
            if (value instanceof JButton) {
                ((JButton) value).doClick();

                if (VentanasAbiertasAdministracionClientes() == true) {
                    ContabilizadorDeVentanasCliente = 1;
                    AdministracionDeCliente ADC = new AdministracionDeCliente(1, Integer.parseInt(TablaClientes.getValueAt(fila, 0).toString()));
                    ADC.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_TablaClientesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel TIPO_BUSQUEDA_MODULO_CLIENTES;
    private static javax.swing.JTable TablaClientes;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane14;
    public static javax.swing.JTextField nombre1;
    // End of variables declaration//GEN-END:variables
}
