/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista.CONFIGURACION;

import CLASES_GLOBALES.METODOS_GLOBALES;
import static CLASES_GLOBALES.METODOS_GLOBALES.CargarDatosRutas;
import static CLASES_GLOBALES.METODOS_GLOBALES.PintarImagen;
import CLASES_GLOBALES.PARAMETROS_EMPRESA;
import Controlador.DatosEmpresaDao;
import FEL.DatosCertificador;
import Modelo.DatosEmpresaGeneral;
import Vista.AVISOS;
import Vista.Principal;
import WebServiceDigifact.ObtenerToken;
import ds.desktop.notify.DesktopNotify;
import ds.desktop.notify.NotifyTheme;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author aldoy
 */
public class EMPRESA extends javax.swing.JInternalFrame {
    PARAMETROS_EMPRESA P_E = new PARAMETROS_EMPRESA();
    Principal principal;
    public EMPRESA(Principal principal) {
        initComponents();
        this.principal = principal;
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }
    
    public void CargarDatosEmpresa(){
        DatosEmpresaDao datosDao= new DatosEmpresaDao();
        datosDao.VerDatos();
        datosDao.VerDatosCertificador();
        PintarImagen(LblImagenEmpresaDocumentos, CargarDatosRutas(0)+"\\" +PARAMETROS_EMPRESA.RUTADEIMAGEN_DOCUMENTOS_EMPRESA);
        PintarImagen(LblImagenEmpresaDocumentos2, CargarDatosRutas(0)+"\\" +PARAMETROS_EMPRESA.RUTADEIMAGEN_DOCUMENTOS_EMPRESA2);
        PintarImagen(LblImagenSistema, METODOS_GLOBALES.CargarDatosRutas(0)+"\\" +PARAMETROS_EMPRESA.RUTADEIMAGEN_SISTEMA_EMPRESA);
        NombreEmpresa.setText(PARAMETROS_EMPRESA.NOMBRE_EMPRESA);
        TituloDatosEmpresa.setText(PARAMETROS_EMPRESA.NOMBRE_EMPRESA);
        NitEmpresa.setText(PARAMETROS_EMPRESA.NIT_EMPRESA);
        DireccionEmpresa.setText(PARAMETROS_EMPRESA.DIRECCION_EMPRESA);
        TelEmpresa.setText(PARAMETROS_EMPRESA.TEL_EMPRESA);
        EsloganEmpresa.setText(PARAMETROS_EMPRESA.ESLOGAN_EMPRESA);
        txtPoliticas.setText(PARAMETROS_EMPRESA.POLITICAS_EMPRESA);
        CorreoEmpresa.setText(PARAMETROS_EMPRESA.CORREO_EMPRESA);
        ContraseniaCorreoEmpresa.setText(PARAMETROS_EMPRESA.CONTRASENIA_EMPRESA);
        IvaEmpresa.setText(PARAMETROS_EMPRESA.IVA_EMPRESA);
        CajaNombreEtiqueta.setText(PARAMETROS_EMPRESA.NOMBRE_EN_ETIQUETA_EMPRESA);
        CajaMunicipioEmpresa.setText(PARAMETROS_EMPRESA.MUNICIPIO_EMPRESA);
        CajaDepartamentoEmpresa.setText(PARAMETROS_EMPRESA.DEPARTAMENTO_EMPRESA);
        CajaPaisEmpresa.setText(PARAMETROS_EMPRESA.PAIS_EMPRESA);
        CajaCodigoPostalEmpresa.setText(PARAMETROS_EMPRESA.CODIGOPOSTAL_EMPRESA);
        CajaAfilicacionEmpresa.setText(PARAMETROS_EMPRESA.AFILICACIONIVA_EMPRESA);
        CajaPropietario.setText(PARAMETROS_EMPRESA.PROPIETARIO_EMPRESA);
        CajaCodigoEstablecimientoEmpresa.setText(PARAMETROS_EMPRESA.CODIGOESTABLECIMIENTO_EMPRESA);
        LblRutaImagenEmpresaDocumentos.setText(PARAMETROS_EMPRESA.RUTADEIMAGEN_DOCUMENTOS_EMPRESA);
        LblrutaImagenSistema.setText(PARAMETROS_EMPRESA.RUTADEIMAGEN_SISTEMA_EMPRESA);
        Uno.setText(PARAMETROS_EMPRESA.UNO);
        Dos.setText(PARAMETROS_EMPRESA.DOS);
        Tres.setText(PARAMETROS_EMPRESA.TRES);
        Cuatro.setText(PARAMETROS_EMPRESA.CUATRO);
        Cinco.setText(PARAMETROS_EMPRESA.CINCO);
        Seis.setText(PARAMETROS_EMPRESA.SEIS);
        Siete.setText(PARAMETROS_EMPRESA.SIETE);
        Ocho.setText(PARAMETROS_EMPRESA.OCHO);
        Nueve.setText(PARAMETROS_EMPRESA.NUEVE);
        Cero.setText(PARAMETROS_EMPRESA.CERO);
        
        
        CajaCertificador.setText(PARAMETROS_EMPRESA.NOMBRE_CERTIFICADOR);
        NitCertificador.setText(PARAMETROS_EMPRESA.NIT_CERTIFICADOR);
        TelefonoCertificador.setText(PARAMETROS_EMPRESA.TELEFONO_CERTIFICADOR);
        CorreoCertificador.setText(PARAMETROS_EMPRESA.CORREO_CERTIFICADOR);
        CajaSesionUsuarioCertificadoraEmpresa.setText(PARAMETROS_EMPRESA.USUARIO_CERTIFICADOR);
        CajaContraseniaCertificadoraEmpresa.setText(PARAMETROS_EMPRESA.CONTRASENIA_CERTIFICADOR);
        CajaToken.setText(PARAMETROS_EMPRESA.TOKEN_CERTIFICADOR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel48 = new javax.swing.JPanel();
        jPanel78 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jLabel94 = new javax.swing.JLabel();
        TituloDatosEmpresa = new javax.swing.JLabel();
        jScrollPane19 = new javax.swing.JScrollPane();
        jPanel79 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        NombreEmpresa = new javax.swing.JTextField();
        jLabel93 = new javax.swing.JLabel();
        NitEmpresa = new javax.swing.JTextField();
        jLabel95 = new javax.swing.JLabel();
        EsloganEmpresa = new javax.swing.JTextField();
        jLabel98 = new javax.swing.JLabel();
        TelEmpresa = new javax.swing.JTextField();
        jLabel97 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        CajaPropietario = new javax.swing.JTextField();
        jLabel101 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        ContraseniaCorreoEmpresa = new javax.swing.JTextField();
        CorreoEmpresa = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        CajaNombreEtiqueta = new javax.swing.JTextField();
        jPanel64 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Uno = new javax.swing.JTextField();
        Dos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Tres = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Cuatro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Cinco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Seis = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Siete = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Ocho = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Nueve = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Cero = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel96 = new javax.swing.JLabel();
        DireccionEmpresa = new javax.swing.JTextField();
        jLabel103 = new javax.swing.JLabel();
        CajaMunicipioEmpresa = new javax.swing.JTextField();
        jLabel104 = new javax.swing.JLabel();
        CajaDepartamentoEmpresa = new javax.swing.JTextField();
        jLabel105 = new javax.swing.JLabel();
        CajaPaisEmpresa = new javax.swing.JTextField();
        jLabel106 = new javax.swing.JLabel();
        CajaCodigoPostalEmpresa = new javax.swing.JTextField();
        jLabel107 = new javax.swing.JLabel();
        CajaAfilicacionEmpresa = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        CajaCodigoEstablecimientoEmpresa = new javax.swing.JTextField();
        jPanel65 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane18 = new javax.swing.JScrollPane();
        txtPoliticas = new javax.swing.JTextArea();
        jPanel24 = new javax.swing.JPanel();
        CajaCertificador = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        NitCertificador = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        TelefonoCertificador = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        CorreoCertificador = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        IvaEmpresa = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jPanel51 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CajaSesionUsuarioCertificadoraEmpresa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CajaContraseniaCertificadoraEmpresa = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        CajaToken = new javax.swing.JTextArea();
        BtnGenerarToken = new javax.swing.JButton();
        jSeparator40 = new javax.swing.JSeparator();
        jSeparator41 = new javax.swing.JSeparator();
        jPanel66 = new javax.swing.JPanel();
        jPanel80 = new javax.swing.JPanel();
        LblRutaImagenEmpresaDocumentos = new javax.swing.JLabel();
        LblImagenEmpresaDocumentos = new javax.swing.JLabel();
        botonseleccionar = new javax.swing.JButton();
        jPanel81 = new javax.swing.JPanel();
        LblrutaImagenSistema = new javax.swing.JLabel();
        LblImagenSistema = new javax.swing.JLabel();
        botonseleccionar1 = new javax.swing.JButton();
        jPanel82 = new javax.swing.JPanel();
        LblRutaImagenEmpresaDocumentos2 = new javax.swing.JLabel();
        LblImagenEmpresaDocumentos2 = new javax.swing.JLabel();
        botonseleccionar2 = new javax.swing.JButton();
        jSeparator42 = new javax.swing.JSeparator();

        setBorder(null);

        jPanel78.setBackground(new java.awt.Color(0, 153, 255));

        jButton15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actualizar Pequeño.png"))); // NOI18N
        jButton15.setText("ACTUALIZAR DATOS");
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actualizar Pequeño.png"))); // NOI18N
        jButton15.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actualizar grande.png"))); // NOI18N
        jButton15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel94.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(230, 0, 0));
        jLabel94.setText("*ESTOS DATOS APARECERAN EN LOS DOCUMENTOS");

        TituloDatosEmpresa.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel78Layout = new javax.swing.GroupLayout(jPanel78);
        jPanel78.setLayout(jPanel78Layout);
        jPanel78Layout.setHorizontalGroup(
            jPanel78Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel78Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel78Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel78Layout.createSequentialGroup()
                        .addComponent(jLabel94)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(TituloDatosEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton15)
                .addContainerGap())
        );
        jPanel78Layout.setVerticalGroup(
            jPanel78Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel78Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel78Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel78Layout.createSequentialGroup()
                        .addComponent(TituloDatosEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel94))
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane19.getVerticalScrollBar().setUnitIncrement(16);

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NombreEmpresa.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        NombreEmpresa.setText("Ferretería El Amigo");

        jLabel93.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel93.setText("EMPRESA:");

        NitEmpresa.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        NitEmpresa.setText("4789627-2");

        jLabel95.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel95.setText("NIT:");

        EsloganEmpresa.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        EsloganEmpresa.setText("\"EL AMIGO DE TU ECONOMÍA\"");

        jLabel98.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel98.setText("ESLOGAN:");

        TelEmpresa.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        TelEmpresa.setText("+502 4035-2573");

        jLabel97.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel97.setText("TEL:");

        jLabel102.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel102.setText("PROPIETARIO:");

        CajaPropietario.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N

        jLabel101.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel101.setText("PASS:");

        jLabel100.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel100.setText("CORREO:");

        ContraseniaCorreoEmpresa.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        ContraseniaCorreoEmpresa.setText("Aldo-40805837");

        CorreoEmpresa.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N

        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("NOMBRE QUE APARECE EN ETIQUETAS:");

        CajaNombreEtiqueta.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel50.setText("DATOS GENERALES");

        javax.swing.GroupLayout jPanel64Layout = new javax.swing.GroupLayout(jPanel64);
        jPanel64.setLayout(jPanel64Layout);
        jPanel64Layout.setHorizontalGroup(
            jPanel64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel64Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel64Layout.setVerticalGroup(
            jPanel64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel64Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel50, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CLAVE DE COSTOS INTERNO *No pueden ser letras repetidas*");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("1");

        Uno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Dos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("2");

        Tres.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("3");

        Cuatro.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("4");

        Cinco.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("5");

        Seis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("6");

        Siete.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("7");

        Ocho.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("8");

        Nueve.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("9");

        Cero.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("0");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel64, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel102, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel93, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel95, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel98, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel97, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CajaPropietario)
                            .addComponent(TelEmpresa)
                            .addComponent(EsloganEmpresa)
                            .addComponent(NitEmpresa)
                            .addComponent(NombreEmpresa)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel101, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel100, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ContraseniaCorreoEmpresa)
                            .addComponent(CorreoEmpresa)))
                    .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CajaNombreEtiqueta)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Uno)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Dos)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Tres)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Cuatro)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Cinco)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Seis)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Siete)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Ocho)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Nueve)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cero, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addComponent(jPanel64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreEmpresa)
                    .addComponent(jLabel93, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CajaPropietario)
                    .addComponent(jLabel102, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NitEmpresa)
                    .addComponent(jLabel95, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EsloganEmpresa)
                    .addComponent(jLabel98, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelEmpresa)
                    .addComponent(jLabel97, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CorreoEmpresa)
                    .addComponent(jLabel100, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContraseniaCorreoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel101, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CajaNombreEtiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Uno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Dos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tres, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Seis, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Siete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );

        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel96.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel96.setText("DIRECCIÓN:");

        DireccionEmpresa.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        DireccionEmpresa.setText("Zona 1, Las Cruces, Petén");

        jLabel103.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel103.setText("MUNICIPIO:");

        CajaMunicipioEmpresa.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N

        jLabel104.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel104.setText("DEPARTAMENTO:");

        CajaDepartamentoEmpresa.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N

        jLabel105.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel105.setText("PAÍS:");

        CajaPaisEmpresa.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N

        jLabel106.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel106.setText("CÓDIGO POSTAL:");

        CajaCodigoPostalEmpresa.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N

        jLabel107.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel107.setText("AFILIACIÓN A IVA:");

        CajaAfilicacionEmpresa.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel23.setText("CÓDIGO DE ESTABLECIMIENTO:");

        CajaCodigoEstablecimientoEmpresa.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N

        jLabel51.setText("DIRECCIONES DE EMPRESA Y PARAMETROS");

        javax.swing.GroupLayout jPanel65Layout = new javax.swing.GroupLayout(jPanel65);
        jPanel65.setLayout(jPanel65Layout);
        jPanel65Layout.setHorizontalGroup(
            jPanel65Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel65Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel65Layout.setVerticalGroup(
            jPanel65Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel65Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel65, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addComponent(jLabel96)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DireccionEmpresa))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                        .addComponent(jLabel103)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CajaMunicipioEmpresa))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                        .addComponent(jLabel104)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CajaDepartamentoEmpresa))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                        .addComponent(jLabel105)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CajaPaisEmpresa))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                        .addComponent(jLabel106)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CajaCodigoPostalEmpresa))
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addComponent(jLabel107)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CajaAfilicacionEmpresa))
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CajaCodigoEstablecimientoEmpresa)))
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DireccionEmpresa)
                    .addComponent(jLabel96, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CajaMunicipioEmpresa)
                    .addComponent(jLabel103, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CajaDepartamentoEmpresa)
                    .addComponent(jLabel104, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CajaPaisEmpresa)
                    .addComponent(jLabel105, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CajaCodigoPostalEmpresa)
                    .addComponent(jLabel106, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CajaAfilicacionEmpresa)
                    .addComponent(jLabel107, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CajaCodigoEstablecimientoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel29.setText("Políticas de la Empresa:");

        txtPoliticas.setColumns(20);
        txtPoliticas.setRows(5);
        jScrollPane18.setViewportView(txtPoliticas);

        jPanel24.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "DATOS CERTIFICADOR:"));

        CajaCertificador.setText("GUATEFACTURAS, SOCIEDAD ANÓNIMA");

        jLabel30.setText("CERTIFICADOR:");

        NitCertificador.setText("CF");

        jLabel33.setText("NIT:");

        TelefonoCertificador.setText("XXXXXX");

        jLabel35.setText("TELÉFONO");

        CorreoCertificador.setText("XXXX@XXXX.COM");

        jLabel36.setText("CORREO");

        IvaEmpresa.setText("12");
        IvaEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IvaEmpresaActionPerformed(evt);
            }
        });

        jLabel67.setText("IVA:");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IvaEmpresa)
                    .addComponent(CorreoCertificador)
                    .addComponent(TelefonoCertificador)
                    .addComponent(NitCertificador)
                    .addComponent(CajaCertificador, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CajaCertificador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NitCertificador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TelefonoCertificador, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CorreoCertificador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IvaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel51.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "SESIÓN EN EMPRESA CERTIFICADORA"));

        jLabel1.setText("USUARIO:");

        jLabel2.setText("CONTRASEÑA:");

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("TOKEN:");

        CajaToken.setEditable(false);
        CajaToken.setColumns(20);
        CajaToken.setRows(5);
        jScrollPane11.setViewportView(CajaToken);

        BtnGenerarToken.setText("GENERAR TOKEN");
        BtnGenerarToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGenerarTokenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel51Layout = new javax.swing.GroupLayout(jPanel51);
        jPanel51.setLayout(jPanel51Layout);
        jPanel51Layout.setHorizontalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel51Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel51Layout.createSequentialGroup()
                        .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CajaSesionUsuarioCertificadoraEmpresa)
                            .addComponent(CajaContraseniaCertificadoraEmpresa)))
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel51Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnGenerarToken)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel51Layout.setVerticalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel51Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CajaSesionUsuarioCertificadoraEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CajaContraseniaCertificadoraEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnGenerarToken, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel66.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "IMAGENES"));

        jPanel80.setBorder(javax.swing.BorderFactory.createTitledBorder("IMAGEN EN DOCUMENTOS"));

        LblRutaImagenEmpresaDocumentos.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        LblRutaImagenEmpresaDocumentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        LblImagenEmpresaDocumentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblImagenEmpresaDocumentos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botonseleccionar.setText("CAMBIAR");
        botonseleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonseleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel80Layout = new javax.swing.GroupLayout(jPanel80);
        jPanel80.setLayout(jPanel80Layout);
        jPanel80Layout.setHorizontalGroup(
            jPanel80Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel80Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblImagenEmpresaDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel80Layout.createSequentialGroup()
                .addGroup(jPanel80Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel80Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblRutaImagenEmpresaDocumentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(botonseleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel80Layout.setVerticalGroup(
            jPanel80Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel80Layout.createSequentialGroup()
                .addComponent(LblImagenEmpresaDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblRutaImagenEmpresaDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonseleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel81.setBorder(javax.swing.BorderFactory.createTitledBorder("IMAGEN EN SISTEMA"));

        LblrutaImagenSistema.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        LblrutaImagenSistema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        LblImagenSistema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblImagenSistema.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botonseleccionar1.setText("CAMBIAR");
        botonseleccionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonseleccionar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel81Layout = new javax.swing.GroupLayout(jPanel81);
        jPanel81.setLayout(jPanel81Layout);
        jPanel81Layout.setHorizontalGroup(
            jPanel81Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel81Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblImagenSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel81Layout.createSequentialGroup()
                .addGroup(jPanel81Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel81Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblrutaImagenSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(botonseleccionar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel81Layout.setVerticalGroup(
            jPanel81Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel81Layout.createSequentialGroup()
                .addComponent(LblImagenSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblrutaImagenSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonseleccionar1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel82.setBorder(javax.swing.BorderFactory.createTitledBorder("IMAGEN EN TICKETS"));

        LblRutaImagenEmpresaDocumentos2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        LblRutaImagenEmpresaDocumentos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        LblImagenEmpresaDocumentos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblImagenEmpresaDocumentos2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botonseleccionar2.setText("CAMBIAR");
        botonseleccionar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonseleccionar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel82Layout = new javax.swing.GroupLayout(jPanel82);
        jPanel82.setLayout(jPanel82Layout);
        jPanel82Layout.setHorizontalGroup(
            jPanel82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel82Layout.createSequentialGroup()
                .addGap(0, 129, Short.MAX_VALUE)
                .addComponent(LblImagenEmpresaDocumentos2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(jPanel82Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonseleccionar2, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addComponent(LblRutaImagenEmpresaDocumentos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel82Layout.setVerticalGroup(
            jPanel82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel82Layout.createSequentialGroup()
                .addComponent(LblImagenEmpresaDocumentos2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblRutaImagenEmpresaDocumentos2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonseleccionar2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel66Layout = new javax.swing.GroupLayout(jPanel66);
        jPanel66.setLayout(jPanel66Layout);
        jPanel66Layout.setHorizontalGroup(
            jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel66Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel66Layout.createSequentialGroup()
                        .addComponent(jPanel80, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel81, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel82, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel66Layout.setVerticalGroup(
            jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel66Layout.createSequentialGroup()
                .addGroup(jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel81, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel79Layout = new javax.swing.GroupLayout(jPanel79);
        jPanel79.setLayout(jPanel79Layout);
        jPanel79Layout.setHorizontalGroup(
            jPanel79Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel79Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel79Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator42)
                    .addComponent(jPanel66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel79Layout.createSequentialGroup()
                        .addComponent(jPanel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane18)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator40)
                    .addComponent(jSeparator41))
                .addContainerGap())
        );
        jPanel79Layout.setVerticalGroup(
            jPanel79Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel79Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator40, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator41, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel79Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator42, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane19.setViewportView(jPanel79);

        javax.swing.GroupLayout jPanel48Layout = new javax.swing.GroupLayout(jPanel48);
        jPanel48.setLayout(jPanel48Layout);
        jPanel48Layout.setHorizontalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel78, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel48Layout.setVerticalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel48Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel78, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane19, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        DatosEmpresaDao datosDao = new DatosEmpresaDao();
        DatosEmpresaGeneral DaEm = new DatosEmpresaGeneral();
        DaEm.setNombreEmpresa(NombreEmpresa.getText());
        DaEm.setNit(NitEmpresa.getText());
        DaEm.setDireccion(DireccionEmpresa.getText());
        DaEm.setTel(TelEmpresa.getText());
        DaEm.setEslogan(EsloganEmpresa.getText());
        DaEm.setPoliticas(txtPoliticas.getText());
        DaEm.setCorreo(CorreoEmpresa.getText());
        DaEm.setContrasenia(ContraseniaCorreoEmpresa.getText());
        DaEm.setIva(IvaEmpresa.getText());
        DaEm.setNombreEtiquetas(CajaNombreEtiqueta.getText());
        DaEm.setPropietario(CajaPropietario.getText());
        DaEm.setMunicipio(CajaMunicipioEmpresa.getText());
        DaEm.setDepartamento(CajaDepartamentoEmpresa.getText());
        DaEm.setPais(CajaPaisEmpresa.getText());
        DaEm.setCodigoPostal(CajaCodigoPostalEmpresa.getText());
        DaEm.setCajaAfilicacionEmpresa(CajaAfilicacionEmpresa.getText());
        DaEm.setCodigoEstablecimiento(CajaCodigoEstablecimientoEmpresa.getText());
        DaEm.setRutaimagenlogo(LblRutaImagenEmpresaDocumentos.getText());
        DaEm.setRutaimagenlogo2(LblRutaImagenEmpresaDocumentos2.getText());
        DaEm.setRutaimagensistema(LblrutaImagenSistema.getText());
        DaEm.setClaveInternaCostos(Uno.getText()+ Dos.getText()+ Tres.getText()+ Cuatro.getText()+ 
                Cinco.getText()+ Seis.getText()+ Siete.getText()+ Ocho.getText()+Nueve.getText()+ Cero.getText());
        datosDao.ActualizarDatos(DaEm);

        DatosCertificador DaCertificador = new DatosCertificador();
        DaCertificador.setNombreCertificador(CajaCertificador.getText());
        DaCertificador.setNitCertificador(NitCertificador.getText());
        DaCertificador.setTelefonoCertificador(TelefonoCertificador.getText());
        DaCertificador.setCorreoCertificador(CorreoCertificador.getText());
        DaCertificador.setUsuarioToken(CajaSesionUsuarioCertificadoraEmpresa.getText());
        DaCertificador.setContraseniaToken(CajaContraseniaCertificadoraEmpresa.getText());
        datosDao.ActualizarDatosCertificador(DaCertificador);
        
        CargarDatosEmpresa();
        
        DesktopNotify.setDefaultTheme(NotifyTheme.Light);
        DesktopNotify.showDesktopMessage("¡PROCESO EXITOSO!", "LOS DATOS SE ACTUALIZARON CORRECTAMENTE",DesktopNotify.INFORMATION, 14000L);
        
        principal.CARGAR_TITULO();

    }//GEN-LAST:event_jButton15ActionPerformed

    private void IvaEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IvaEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IvaEmpresaActionPerformed

    private void BtnGenerarTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGenerarTokenActionPerformed

        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                AVISOS AV = new AVISOS("CARGANDO DATOS", "POR FAVOR, ESPERE");
                AV.setVisible(true);

                Runnable runnable2 = new Runnable() {
                    @Override
                    public void run() {
                        ObtenerToken OT = new ObtenerToken();
                        OT.ObtenerToken();
                        AV.dispose();
                        CajaToken.setText(PARAMETROS_EMPRESA.TOKEN_CERTIFICADOR);
                    }
                };
                Thread hilo2 = new Thread(runnable2);
                hilo2.start();

            }
        };
        Thread hilo = new Thread(runnable);
        hilo.start();
    }//GEN-LAST:event_BtnGenerarTokenActionPerformed

    private void botonseleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonseleccionarActionPerformed
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Formatos PNG, JPG Y JPEG(*.PNG;*.JPG;*.JPEG)", "PNG", "JPG", "JPEG");
        FileNameExtensionFilter filtro2 = new FileNameExtensionFilter("JPEG(*.JPEG)", "JPEG");
        FileNameExtensionFilter filtro3 = new FileNameExtensionFilter("JPG(*.JPG;)", "JPG");
        FileNameExtensionFilter filtro4 = new FileNameExtensionFilter("PNG(*.PNG;)", "PNG");
        JFileChooser archivo = new JFileChooser();
        archivo.setCurrentDirectory(new File(METODOS_GLOBALES.CargarDatosRutasAlBuscarImagen()));
        archivo.addChoosableFileFilter(filtro);
        archivo.addChoosableFileFilter(filtro2);
        archivo.addChoosableFileFilter(filtro3);
        archivo.addChoosableFileFilter(filtro4);
        archivo.setFileFilter(filtro);
        archivo.setDialogTitle("SELECCIONE UNA IMAGEN");
        int ventana = archivo.showOpenDialog(null);
        if (ventana == JFileChooser.APPROVE_OPTION) {
            try {
                File file = archivo.getSelectedFile();
                String DestinoPath = CargarDatosRutas(0) + "\\"+ file.getName();
                Path Destino = Paths.get(DestinoPath);

                String OrigenPath = file.getPath();
                Path Origen = Paths.get(OrigenPath);

                Files.copy(Origen, Destino, StandardCopyOption.REPLACE_EXISTING);
                javax.swing.JOptionPane.showMessageDialog(null, "EL ARCHIVO FUÉ COPIADO EN "+ DestinoPath);
                LblRutaImagenEmpresaDocumentos.setText(file.getName());
                PintarImagen(LblImagenEmpresaDocumentos, CargarDatosRutas(0) + "\\"+LblRutaImagenEmpresaDocumentos.getText());
                } catch (IOException ex) {
                    System.out.println("ERROR \n"+ex);
                }
            }
    }//GEN-LAST:event_botonseleccionarActionPerformed

    private void botonseleccionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonseleccionar1ActionPerformed
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Formatos PNG, JPG Y JPEG(*.PNG;*.JPG;*.JPEG)", "PNG", "JPG", "JPEG");
        FileNameExtensionFilter filtro2 = new FileNameExtensionFilter("JPEG(*.JPEG)", "JPEG");
        FileNameExtensionFilter filtro3 = new FileNameExtensionFilter("JPG(*.JPG;)", "JPG");
        FileNameExtensionFilter filtro4 = new FileNameExtensionFilter("PNG(*.PNG;)", "PNG");
        JFileChooser archivo = new JFileChooser();
        archivo.setCurrentDirectory(new File(METODOS_GLOBALES.CargarDatosRutasAlBuscarImagen()));
        archivo.addChoosableFileFilter(filtro);
        archivo.addChoosableFileFilter(filtro2);
        archivo.addChoosableFileFilter(filtro3);
        archivo.addChoosableFileFilter(filtro4);
        archivo.setFileFilter(filtro);
        archivo.setDialogTitle("SELECCIONE UNA IMAGEN");
        int ventana = archivo.showOpenDialog(null);
        if (ventana == JFileChooser.APPROVE_OPTION) {
            try {
                File file = archivo.getSelectedFile();
                String DestinoPath = CargarDatosRutas(0) + "\\"+ file.getName();
                Path Destino = Paths.get(DestinoPath);

                String OrigenPath = file.getPath();
                Path Origen = Paths.get(OrigenPath);

                Files.copy(Origen, Destino, StandardCopyOption.REPLACE_EXISTING);
                javax.swing.JOptionPane.showMessageDialog(null, "EL ARCHIVO FUÉ COPIADO EN "+ DestinoPath);
                LblrutaImagenSistema.setText(file.getName());
                PintarImagen(LblImagenSistema, CargarDatosRutas(0) + "\\"+LblrutaImagenSistema.getText());
                } catch (IOException ex) {
                    System.out.println("ERROR \n"+ex);
                }
            }
    }//GEN-LAST:event_botonseleccionar1ActionPerformed

    private void botonseleccionar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonseleccionar2ActionPerformed
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Formatos PNG, JPG Y JPEG(*.PNG;*.JPG;*.JPEG)", "PNG", "JPG", "JPEG");
        FileNameExtensionFilter filtro2 = new FileNameExtensionFilter("JPEG(*.JPEG)", "JPEG");
        FileNameExtensionFilter filtro3 = new FileNameExtensionFilter("JPG(*.JPG;)", "JPG");
        FileNameExtensionFilter filtro4 = new FileNameExtensionFilter("PNG(*.PNG;)", "PNG");
        JFileChooser archivo = new JFileChooser();
        archivo.setCurrentDirectory(new File(METODOS_GLOBALES.CargarDatosRutasAlBuscarImagen()));
        archivo.addChoosableFileFilter(filtro);
        archivo.addChoosableFileFilter(filtro2);
        archivo.addChoosableFileFilter(filtro3);
        archivo.addChoosableFileFilter(filtro4);
        archivo.setFileFilter(filtro);
        archivo.setDialogTitle("SELECCIONE UNA IMAGEN");
        int ventana = archivo.showOpenDialog(null);
        if (ventana == JFileChooser.APPROVE_OPTION) {
            try {
                File file = archivo.getSelectedFile();
                String DestinoPath = CargarDatosRutas(0) + "\\"+ file.getName();
                Path Destino = Paths.get(DestinoPath);

                String OrigenPath = file.getPath();
                Path Origen = Paths.get(OrigenPath);

                Files.copy(Origen, Destino, StandardCopyOption.REPLACE_EXISTING);
                javax.swing.JOptionPane.showMessageDialog(null, "EL ARCHIVO FUÉ COPIADO EN "+ DestinoPath);
                LblRutaImagenEmpresaDocumentos2.setText(file.getName());
                PintarImagen(LblImagenEmpresaDocumentos2, CargarDatosRutas(0) + "\\"+LblRutaImagenEmpresaDocumentos2.getText());
                } catch (IOException ex) {
                    System.out.println("ERROR \n"+ex);
                }
            }
    }//GEN-LAST:event_botonseleccionar2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGenerarToken;
    public static javax.swing.JTextField CajaAfilicacionEmpresa;
    public static javax.swing.JTextField CajaCertificador;
    public static javax.swing.JTextField CajaCodigoEstablecimientoEmpresa;
    public static javax.swing.JTextField CajaCodigoPostalEmpresa;
    public static javax.swing.JTextField CajaContraseniaCertificadoraEmpresa;
    public static javax.swing.JTextField CajaDepartamentoEmpresa;
    public static javax.swing.JTextField CajaMunicipioEmpresa;
    public static javax.swing.JTextField CajaNombreEtiqueta;
    public static javax.swing.JTextField CajaPaisEmpresa;
    public static javax.swing.JTextField CajaPropietario;
    public static javax.swing.JTextField CajaSesionUsuarioCertificadoraEmpresa;
    public static javax.swing.JTextArea CajaToken;
    private javax.swing.JTextField Cero;
    private javax.swing.JTextField Cinco;
    private static javax.swing.JTextField ContraseniaCorreoEmpresa;
    private static javax.swing.JTextField CorreoCertificador;
    private static javax.swing.JTextField CorreoEmpresa;
    private javax.swing.JTextField Cuatro;
    public static javax.swing.JTextField DireccionEmpresa;
    private javax.swing.JTextField Dos;
    private static javax.swing.JTextField EsloganEmpresa;
    private static javax.swing.JTextField IvaEmpresa;
    private static javax.swing.JLabel LblImagenEmpresaDocumentos;
    private static javax.swing.JLabel LblImagenEmpresaDocumentos2;
    private static javax.swing.JLabel LblImagenSistema;
    private static javax.swing.JLabel LblRutaImagenEmpresaDocumentos;
    private static javax.swing.JLabel LblRutaImagenEmpresaDocumentos2;
    private static javax.swing.JLabel LblrutaImagenSistema;
    public static javax.swing.JTextField NitCertificador;
    public static javax.swing.JTextField NitEmpresa;
    public static javax.swing.JTextField NombreEmpresa;
    private javax.swing.JTextField Nueve;
    private javax.swing.JTextField Ocho;
    private javax.swing.JTextField Seis;
    private javax.swing.JTextField Siete;
    private static javax.swing.JTextField TelEmpresa;
    private static javax.swing.JTextField TelefonoCertificador;
    private static javax.swing.JLabel TituloDatosEmpresa;
    private javax.swing.JTextField Tres;
    private javax.swing.JTextField Uno;
    private javax.swing.JButton botonseleccionar;
    private javax.swing.JButton botonseleccionar1;
    private javax.swing.JButton botonseleccionar2;
    private javax.swing.JButton jButton15;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    public static javax.swing.JPanel jPanel13;
    public static javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel24;
    public javax.swing.JPanel jPanel48;
    public static javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel78;
    private javax.swing.JPanel jPanel79;
    private javax.swing.JPanel jPanel80;
    private javax.swing.JPanel jPanel81;
    private javax.swing.JPanel jPanel82;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator42;
    public static javax.swing.JTextArea txtPoliticas;
    // End of variables declaration//GEN-END:variables
}
