package CLASES_GLOBALES;

public class PARAMETROS_USUARIOS {
            
    public static int ID_USUARIO;
    public static String NOMBRE_USUARIO, NOMBREVISTA_USUARIO, CONTRASENIA_USUARIO, CORREO, CONTRASENIA_CORREO, 
            ROL_USUARIO, ULTIMAVEZINGRESO_USUARIO, RUTAIMAGEN_USUARIO, FECHAINGRESO_USUARIO, ESTADO, ESTADO_USUARIO, COLOR_USUARIO="#FFFFFF";
    
}
