package CLASES_GLOBALES;

public class PARAMETROS_USUARIOS {
            
    public static int ID_USUARIO;
    public static String NOMBRE_USUARIO, NOMBREVISTA_USUARIO, CONTRASENIA_USUARIO, ROL_USUARIO, ULTIMAVEZINGRESO_USUARIO, RUTAIMAGEN_USUARIO, FECHAINGRESO_USUARIO, ESTADO_USUARIO;
    
}
